pub mod graph;
pub mod enhanced_graph;
pub mod graph_serde;
pub mod lsif;
pub mod call_hierarchy;
pub mod incremental;
pub mod definition_chain;
pub mod type_relations;
pub mod graph_query;
pub mod parallel;
pub mod parallel_optimized;

pub use graph::{CodeGraph, Symbol, SymbolKind, Range, Position, EdgeKind};
pub use enhanced_graph::{EnhancedCodeGraph, TypeInfo, CallInfo, CallHierarchy as EnhancedCallHierarchy, CallNode, TypeRelations as EnhancedTypeRelations};
pub use lsif::{generate_lsif, parse_lsif, write_lsif};
pub use call_hierarchy::{CallHierarchy, CallHierarchyAnalyzer, format_hierarchy};
pub use incremental::{IncrementalIndex, FileUpdate, UpdateResult, BatchUpdateResult, calculate_file_hash};
pub use definition_chain::{DefinitionChain, DefinitionChainAnalyzer, format_definition_chain};
pub use type_relations::{TypeRelations, TypeRelationsAnalyzer, TypeHierarchy, RelationGroups, format_type_relations};
pub use graph_query::{QueryPattern, QueryParser, QueryEngine, QueryResult, format_query_results};