name: Update Badges

on:
  push:
    branches: [ main ]
  workflow_run:
    workflows: ["CI"]
    types:
      - completed

jobs:
  update-badges:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' || github.event.workflow_run.conclusion == 'success'
    steps:
      - uses: actions/checkout@v4
      
      - name: Create badges directory
        run: mkdir -p .github/badges
        
      - name: Generate test badge
        uses: emibcn/badge-action@v2.0.2
        with:
          label: 'tests'
          status: 'passing'
          color: 'green'
          path: '.github/badges/tests.svg'
          
      - name: Generate build badge
        uses: emibcn/badge-action@v2.0.2
        with:
          label: 'build'
          status: 'passing'
          color: 'green'
          path: '.github/badges/build.svg'
          
      - name: Commit badge changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .github/badges
          git diff --quiet && git diff --staged --quiet || git commit -m "chore: update badges [skip ci]"
          
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
        continue-on-error: true